package spacetrader.game.quest.enums;

public enum EventName {

    AFTER_GAME_INITIALIZE,          // After full game initialization
    ON_BEFORE_SPECIAL_BUTTON_SHOW,     // Before show Special button on System Info Panel
    ON_SPECIAL_BUTTON_CLICKED,          // On Special button clicked
    ON_ARRESTED,
    ON_ESCAPE_WITH_POD,
    ON_GENERATE_CREW_MEMBER_LIST,
    ON_INCREMENT_DAYS,
    IS_CONSIDER_STATUS_CHEAT,
    IS_CONSIDER_STATUS_DEFAULT_CHEAT,
    ON_DISPLAY_SPECIAL_CARGO,
    ON_GET_QUESTS_STRINGS,
    ON_ASSIGN_EVENTS_RANDOMLY,
    ON_ASSIGN_EVENTS_MANUAL,
    ON_DETERMINE_NON_RANDOM_ENCOUNTER,
    ON_NEWS_ADD_EVENT_ON_ARRIVAL,
    ON_CREATE_SHIP,
    ON_ENCOUNTER_EXECUTE_ACTION_OPPONENT_DISABLED,
    ON_ENCOUNTER_EXECUTE_ATTACK_KEEP_SPECIAL_SHIP,
    ON_ENCOUNTER_VERIFY_ATTACK,
    ON_ENCOUNTER_VERIFY_SURRENDER_NO_HIDDEN,
    ON_ENCOUNTER_VERIFY_SURRENDER_HIDDEN,
    ON_GET_ENCOUNTER_TEXT_INITIAL,
    ON_GET_STEALABLE_CARGO,
    ON_GET_GAME_SCORE,
    AFTER_SHIP_SPECS_INITIALIZED,
    ON_BEFORE_GAME_END,
    ON_GAME_END_ALERT
}
